baseURL = "https://vineetloomba.com/"
languageCode = "en-us"
title = "Vineet Loomba LMS"
theme = "compose"

[params]
  author = "Vineet Loomba"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
