backend:
  name: github
  repo: vineetl007/vineetloomba
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "YouTube Link", name: "youtube", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
