backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "chapters"
    label: "Chapters"
    folder: "content/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "concepts"
    label: "Concepts"
    folder: "content/chapters/calculus"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "YouTube Video Embed Link", name: "youtube", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
